import type { Metadata } from "next";
import { Montserrat, Mulish } from "next/font/google";
import "./globals.css";
import { StaysProvider } from "@/app/context/staysProvider";

// come back to this - mulish and anti-aliasing

const montserrat = Montserrat({
  subsets: ["latin"],
  // weight: ["500", "700"],
});

const mulish = Mulish({
  subsets: ["latin"],
  // weight: ["500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <StaysProvider>
        <body className={`${montserrat.className} ${mulish.className}`}>
          {children}
        </body>
      </StaysProvider>
    </html>
  );
}
